version: '3.7'

services:
  mysql:
    build: ./
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    command: --authentication_policy=mysql_native_password
    restart: always
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      - ./dump:/disk
    ports:
      - 33061:3306
